# Penetration Testing Configuration
# This file contains configuration settings for the penetration testing system

# Safety and Security Settings
safety:
  # Safety level: low, medium, high, critical
  level: "high"
  
  # Resource limits
  limits:
    max_concurrent_scans: 5
    max_scan_rate: 100  # packets per second
    max_session_duration: 3600  # seconds (1 hour)
    max_memory_usage: 1024  # MB
    max_cpu_usage: 0.8  # 80%
    max_network_bandwidth: 10  # Mbps
  
  # Allowed and blocked ports
  ports:
    allowed:
      - 21    # FTP
      - 22    # SSH
      - 23    # Telnet
      - 25    # SMTP
      - 53    # DNS
      - 80    # HTTP
      - 110   # POP3
      - 143   # IMAP
      - 443   # HTTPS
      - 993   # IMAPS
      - 995   # POP3S
      - 8080  # HTTP Alt
      - 8443  # HTTPS Alt
      - 3389  # RDP
      - 5432  # PostgreSQL
      - 3306  # MySQL
      - 1433  # MSSQL
      - 27017 # MongoDB
    
    blocked:
      - 0     # Reserved
      - 1     # TCPMUX
      - 7     # Echo
      - 9     # Discard
      - 13    # Daytime
      - 17    # Quote
      - 19    # Chargen
      - 20    # FTP Data
      - 37    # Time
      - 42    # WINS
      - 43    # WHOIS
      - 49    # TACACS
      - 135   # RPC
      - 136   # NetBIOS
      - 137   # NetBIOS
      - 138   # NetBIOS
      - 139   # NetBIOS
      - 445   # SMB

# Target Validation Settings
target_validation:
  # Require explicit authorization
  require_authorization: true
  
  # Blocked networks (CIDR notation)
  blocked_networks:
    - "127.0.0.0/8"     # Localhost
    - "169.254.0.0/16"  # Link-local
    - "224.0.0.0/4"     # Multicast
    - "240.0.0.0/4"     # Reserved
  
  # Require confirmation for private networks
  private_network_confirmation: true
  
  # DNS validation
  dns_validation:
    enabled: true
    timeout: 5  # seconds
  
  # WHOIS validation
  whois_validation:
    enabled: true
    timeout: 10  # seconds

# Command Filtering Settings
command_filter:
  # Whitelist mode (only allow explicitly listed commands)
  whitelist_mode: true
  
  # Allowed commands
  allowed_commands:
    - "nmap"
    - "ping"
    - "dig"
    - "nslookup"
    - "whois"
    - "curl"
    - "wget"
  
  # Blocked command patterns
  blocked_patterns:
    - "rm -rf"
    - "dd if="
    - "mkfs"
    - "format"
    - "del /f"
    - "shutdown"
    - "reboot"
    - "halt"
  
  # Dangerous argument patterns
  dangerous_args:
    - "--script=*exploit*"
    - "--script=*dos*"
    - "--script=*flood*"
    - "-sU -p-"  # Full UDP scan
    - "-T5"      # Insane timing

# Nmap Configuration
nmap:
  # Default scan profiles
  profiles:
    discovery:
      args: "-sn"
      description: "Ping scan only"
      risk_level: "low"
    
    quick:
      args: "-T4 -F"
      description: "Fast scan of common ports"
      risk_level: "low"
    
    comprehensive:
      args: "-T4 -A -v"
      description: "Comprehensive scan with OS detection"
      risk_level: "medium"
    
    stealth:
      args: "-sS -T2"
      description: "Stealth SYN scan"
      risk_level: "medium"
    
    udp:
      args: "-sU --top-ports 100"
      description: "UDP scan of top 100 ports"
      risk_level: "medium"
    
    version:
      args: "-sV"
      description: "Version detection"
      risk_level: "low"
    
    os:
      args: "-O"
      description: "OS detection"
      risk_level: "low"
    
    script:
      args: "-sC"
      description: "Default scripts"
      risk_level: "medium"
  
  # Timing templates
  timing:
    paranoid: "-T0"   # Very slow
    sneaky: "-T1"     # Slow
    polite: "-T2"     # Normal
    normal: "-T3"     # Default
    aggressive: "-T4" # Fast
    insane: "-T5"     # Very fast (not recommended)
  
  # Default timeouts
  timeouts:
    host_timeout: "30m"
    scan_delay: "0"
    max_retries: 3

# Bright Data OSINT Configuration
bright_data:
  # OSINT capabilities
  osint:
    # Social media intelligence
    social_media:
      enabled: true
      platforms:
        - "linkedin"
        - "twitter"
        - "facebook"
        - "instagram"
      rate_limit: 10  # requests per minute
    
    # Domain intelligence
    domain_intel:
      enabled: true
      sources:
        - "certificate_transparency"
        - "dns_databases"
        - "subdomain_enumeration"
      max_subdomains: 1000
    
    # Dark web monitoring
    dark_web:
      enabled: false  # Requires special authorization
      sources:
        - "tor_sites"
        - "credential_dumps"
        - "threat_feeds"
      risk_level: "critical"
    
    # Threat intelligence
    threat_intel:
      enabled: true
      sources:
        - "malware_databases"
        - "ip_reputation"
        - "domain_reputation"
      cache_duration: 3600  # seconds

# Reporting Configuration
reporting:
  # Report formats
  formats:
    - "html"
    - "pdf"
    - "json"
    - "xml"
  
  # Report sections
  sections:
    - "executive_summary"
    - "methodology"
    - "findings"
    - "recommendations"
    - "technical_details"
    - "appendices"
  
  # Severity levels
  severity_levels:
    - "critical"
    - "high"
    - "medium"
    - "low"
    - "informational"
  
  # Report templates
  templates:
    executive: "templates/executive_report.html"
    technical: "templates/technical_report.html"
    compliance: "templates/compliance_report.html"

# Logging Configuration
logging:
  # Log levels
  level: "INFO"
  
  # Log files
  files:
    main: "logs/pentest_main.log"
    security: "logs/pentest_security.log"
    audit: "logs/pentest_audit.log"
    errors: "logs/pentest_errors.log"
  
  # Log rotation
  rotation:
    max_size: "100MB"
    backup_count: 10
  
  # Audit logging
  audit:
    enabled: true
    log_all_commands: true
    log_all_targets: true
    log_all_results: true

# Notification Configuration
notifications:
  # Email notifications
  email:
    enabled: false
    smtp_server: "smtp.example.com"
    smtp_port: 587
    username: "pentest@example.com"
    recipients:
      - "security-team@example.com"
  
  # Webhook notifications
  webhook:
    enabled: false
    url: "https://hooks.example.com/pentest"
    events:
      - "session_started"
      - "critical_finding"
      - "session_completed"
      - "emergency_stop"

# Integration Configuration
integrations:
  # SIEM integration
  siem:
    enabled: false
    type: "splunk"  # splunk, elastic, qradar
    endpoint: "https://siem.example.com"
    api_key: "your-api-key"
  
  # Ticketing system
  ticketing:
    enabled: false
    type: "jira"  # jira, servicenow, github
    endpoint: "https://tickets.example.com"
    project: "PENTEST"
  
  # Vulnerability management
  vuln_mgmt:
    enabled: false
    type: "tenable"  # tenable, qualys, rapid7
    endpoint: "https://vulns.example.com"
    api_key: "your-api-key"
