name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'docs/**'
      - 'README.md'
      - 'mkdocs.yml'

jobs:
  # Job 1: Build Documentation
  build-docs:
    name: Build Documentation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material mkdocs-mermaid2-plugin

    - name: Build documentation
      run: |
        mkdocs build || echo "Documentation build completed with issues"
      continue-on-error: true

    - name: Upload documentation artifacts
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: documentation
        path: site/


